# kubectl create secret tls awx-tls-secret --cert=STAR_singhritesh85_com.crt --key=mykey.key -n awx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ansible-awx-ingress
  namespace: awx
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: azure-application-gateway
  tls:
  - secretName: awx-tls-secret
  rules:
  - host: ansible-awx.singhritesh85.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ansible-awx-service
            port:
              number: 80
