# kubectl create secret tls awx-tls-secret --cert=f58ce5a18a182d4b.crt --key=server.key -n awx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awx-ingress
  namespace: awx
  annotations:
    kubernetes.io/ingress.class: "gce" # Specify the Ingress class
    kubernetes.io/ingress.allow-http: "false"
#    cloud.google.com/backend-config: '{"default": "bankapp-backendconfig"}'
spec:
  ingressClassName: "gce"
  tls:
  - hosts:
    - ansible-awx.singhritesh85.com
    secretName: awx-tls-secret
  rules:
  - host: "ansible-awx.singhritesh85.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ansible-awx-service
            port:
              number: 80
